### ISSUE TITLE
Question: is it working?

### ISSUE THREAD

**Issue by xivilay** [AZSlow3/FluidSynthVST#2]
Hello, 
I tried the provided binary with different VST hosts, including _Cantabile 3_, _Ableton 10 Lite_, and _Steinberg VST3PluginTestHost 3.0.0.31_ under _win10x64_, but it seems the plugin doesn't receive midi input. I tried several different fonts.
I've built the plugin with _glib 2.62.0_, _fluidsynth 2.0.5_ and _vst sdk 3.7.1_, but still no luck. May be I am doing something wrong?

P.S. When I was searching for examples of vst sdk, I've found another nice vst plugin with gui called _Utsbox SF2 Player_. Hope it may help anyone who is searching for similar functionality.

**Comment by AZSlow3** [comment]
This plug-in was written specially to work in REAPER, under Linux and Windows. While there is nothing special for REAPER, it was not tested with other DAWs and for some reason it doesn't work with any other DAW I have tried.
I hope to fix that at some point, but that has no priority at the moment.

**Comment by AZSlow3** [comment]
The last bug-fix has made it at least somehow work in Cakewalk... Probably in other DAWs.
